### ISSUE TITLE
DOSBox Wii 1.7 r1 update

### ISSUE THREAD

**Issue by niuus** [retro100/dosbox-wii#2]
Hi retro100. You're doing a great service to the community by reviving this port on the Wii.

Just thought you might have interest on integrating the very useful minor updates made by Wiimpathy some years ago, listed below:

> /* DOSBox Wii Version 1.7 R1 (wiimpathy) */
> R1 - April 1, 2016
> ------------------
> 
> * GameCube pad support in-game : add joystick=fcs in Dosbox .conf file.
> * Navigate menu with GC pad, open it with Start+Z.
> * Mapper button to remap keyboard/controllers(same as CTRL-F1).
> * New top menu buttons, from left to right: cycles, frameskip, scaler.
>   Push + or - to increase/decrease cycles/frameskip. Push the tv button to change the filter.
> * Conf file saved automatically when exiting if values have been modified("config -wc")

A little bug crawled in, which replaces **scaler=none** to **scaler=normal2x** if you changed any setting (i.e. _cycles_) while running.

I have a copy of the patch which he posted on the forums, so if you want to merge it with your update, just lemme know.

**Comment by retro100** [comment]
Hi!
Please send me the link to the forum entry where the patch is posted. If the forum entry doesn't exist any more then please provide me the patch file as code snippet on github or on another public platform. Or maybe Wiimpathy can provide the patch or the modified version on github as a repo.

**Comment by niuus** [comment]
There never was a Github. [Public forum entry](https://gbatemp.net/threads/wiiflow-lite.422685/page-76#post-8580238).

**Comment by retro100** [comment]
Thanks for the link! I now have tested the modified version from Wiimpathy.

The features from Wiimpathy version are really amazing!

I create a new branch https://github.com/retro100/dosbox-wii/tree/v1-7_r1_wiimpathy and some mal changes to compile with the current devkitPro version. The v1-7_r1_wiimpathy branch doesn't include the updated dosbox-wii version with dynrec support. The branch is only for testing the Wiimpathy version.

I hope to have time soon to integrate the changes into the updated dosbox-wii version with dynrec support at the master branch ;-)

**Comment by niuus** [comment]
> Thanks for the link! I now have tested the modified version from Wiimpathy.
> 
> The features from Wiimpathy version are really amazing!
> 
> I create a new branch https://github.com/retro100/dosbox-wii/tree/v1-7_r1_wiimpathy and some mal changes to compile with the current devkitPro version. The v1-7_r1_wiimpathy branch doesn't include the updated dosbox-wii version with dynrec support. The branch is only for testing the Wiimpathy version.
> 
> I hope to have time soon to integrate the changes into the updated dosbox-wii version with dynrec support at the master branch ;-)

Awesome, man. Thanks for your cool work, i'll now go and test your recent Beta 2. :-D

**Comment by niuus** [comment]
Implemented and working since 1.7x Beta 3 r4301. Thanks!

**Comment by retro100** [comment]
I hope to implement the rest of the 1.7 R1 (wiimpathy) features soon. (Mapper button, saving config changes, scaler button)
